package util

case class RecivedData(timeStamp:String,
                       srcIp:String,
                       desIp:String,
                       duration:Double,
                       protocol_type:String,
                       service:String,
                       flag:String,
                       src_bytes:Double,
                       dst_bytes:Double,
                       land:String,
                       wrong_fragment:Double,
                       urgent:Double,
                       count:Double,
                       srv_count:Double,
                       serror_rate:Double,
                       srv_serror_rate:Double,
                       rerror_rate:Double,
                       srv_rerror_rate:Double,
                       same_srv_rate:Double,
                       diff_srv_rate:Double,
                       srv_diff_host_rate:Double,
                       dst_host_count:Double,
                       dst_host_srv_count:Double,
                       dst_host_same_srv_rate:Double,
                       dst_host_diff_srv_rate:Double,
                       dst_host_same_src_port_rate:Double,
                       dst_host_srv_diff_host_rate:Double,
                       dst_host_serror_rate:Double,
                       dst_host_srv_serror_rate:Double,
                       dst_host_rerror_rate:Double,
                       dst_host_srv_rerror_rate:Double)

